/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChambersRouteImport } from './routes/chambers'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppointmentRouteImport } from './routes/appointment'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthenticatedPatientRouteImport } from './routes/_authenticated/patient'
import { Route as AuthenticatedDoctorRouteImport } from './routes/_authenticated/doctor'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPatientIndexRouteImport } from './routes/_authenticated/patient.index'
import { Route as AuthenticatedDoctorIndexRouteImport } from './routes/_authenticated/doctor.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedPatientProfileRouteImport } from './routes/_authenticated/patient.profile'
import { Route as AuthenticatedPatientPrescriptionsRouteImport } from './routes/_authenticated/patient.prescriptions'
import { Route as AuthenticatedPatientHistoryRouteImport } from './routes/_authenticated/patient.history'
import { Route as AuthenticatedPatientAppointmentsRouteImport } from './routes/_authenticated/patient.appointments'
import { Route as AuthenticatedDoctorUsersRouteImport } from './routes/_authenticated/doctor.users'
import { Route as AuthenticatedDoctorSettingsRouteImport } from './routes/_authenticated/doctor.settings'
import { Route as AuthenticatedDoctorReportsRouteImport } from './routes/_authenticated/doctor.reports'
import { Route as AuthenticatedDoctorPrescriptionsRouteImport } from './routes/_authenticated/doctor.prescriptions'
import { Route as AuthenticatedDoctorPatientsRouteImport } from './routes/_authenticated/doctor.patients'
import { Route as AuthenticatedDoctorAppointmentsRouteImport } from './routes/_authenticated/doctor.appointments'
import { Route as AuthenticatedAdminWebsiteRouteImport } from './routes/_authenticated/admin.website'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminAppointmentsRouteImport } from './routes/_authenticated/admin.appointments'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChambersRoute = ChambersRouteImport.update({
  id: '/chambers',
  path: '/chambers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentRoute = AppointmentRouteImport.update({
  id: '/appointment',
  path: '/appointment',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedPatientRoute = AuthenticatedPatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDoctorRoute = AuthenticatedDoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPatientIndexRoute =
  AuthenticatedPatientIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPatientRoute,
  } as any)
const AuthenticatedDoctorIndexRoute =
  AuthenticatedDoctorIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDoctorRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedPatientProfileRoute =
  AuthenticatedPatientProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedPatientRoute,
  } as any)
const AuthenticatedPatientPrescriptionsRoute =
  AuthenticatedPatientPrescriptionsRouteImport.update({
    id: '/prescriptions',
    path: '/prescriptions',
    getParentRoute: () => AuthenticatedPatientRoute,
  } as any)
const AuthenticatedPatientHistoryRoute =
  AuthenticatedPatientHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedPatientRoute,
  } as any)
const AuthenticatedPatientAppointmentsRoute =
  AuthenticatedPatientAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedPatientRoute,
  } as any)
const AuthenticatedDoctorUsersRoute =
  AuthenticatedDoctorUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedDoctorRoute,
  } as any)
const AuthenticatedDoctorSettingsRoute =
  AuthenticatedDoctorSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDoctorRoute,
  } as any)
const AuthenticatedDoctorReportsRoute =
  AuthenticatedDoctorReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedDoctorRoute,
  } as any)
const AuthenticatedDoctorPrescriptionsRoute =
  AuthenticatedDoctorPrescriptionsRouteImport.update({
    id: '/prescriptions',
    path: '/prescriptions',
    getParentRoute: () => AuthenticatedDoctorRoute,
  } as any)
const AuthenticatedDoctorPatientsRoute =
  AuthenticatedDoctorPatientsRouteImport.update({
    id: '/patients',
    path: '/patients',
    getParentRoute: () => AuthenticatedDoctorRoute,
  } as any)
const AuthenticatedDoctorAppointmentsRoute =
  AuthenticatedDoctorAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedDoctorRoute,
  } as any)
const AuthenticatedAdminWebsiteRoute =
  AuthenticatedAdminWebsiteRouteImport.update({
    id: '/website',
    path: '/website',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAppointmentsRoute =
  AuthenticatedAdminAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appointment': typeof AppointmentRoute
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRoute
  '/chambers': typeof ChambersRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/portal': typeof PortalRoute
  '/services': typeof ServicesRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/doctor': typeof AuthenticatedDoctorRouteWithChildren
  '/patient': typeof AuthenticatedPatientRouteWithChildren
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/admin/appointments': typeof AuthenticatedAdminAppointmentsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/website': typeof AuthenticatedAdminWebsiteRoute
  '/doctor/appointments': typeof AuthenticatedDoctorAppointmentsRoute
  '/doctor/patients': typeof AuthenticatedDoctorPatientsRoute
  '/doctor/prescriptions': typeof AuthenticatedDoctorPrescriptionsRoute
  '/doctor/reports': typeof AuthenticatedDoctorReportsRoute
  '/doctor/settings': typeof AuthenticatedDoctorSettingsRoute
  '/doctor/users': typeof AuthenticatedDoctorUsersRoute
  '/patient/appointments': typeof AuthenticatedPatientAppointmentsRoute
  '/patient/history': typeof AuthenticatedPatientHistoryRoute
  '/patient/prescriptions': typeof AuthenticatedPatientPrescriptionsRoute
  '/patient/profile': typeof AuthenticatedPatientProfileRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/doctor/': typeof AuthenticatedDoctorIndexRoute
  '/patient/': typeof AuthenticatedPatientIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appointment': typeof AppointmentRoute
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRoute
  '/chambers': typeof ChambersRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/portal': typeof PortalRoute
  '/services': typeof ServicesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/admin/appointments': typeof AuthenticatedAdminAppointmentsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/website': typeof AuthenticatedAdminWebsiteRoute
  '/doctor/appointments': typeof AuthenticatedDoctorAppointmentsRoute
  '/doctor/patients': typeof AuthenticatedDoctorPatientsRoute
  '/doctor/prescriptions': typeof AuthenticatedDoctorPrescriptionsRoute
  '/doctor/reports': typeof AuthenticatedDoctorReportsRoute
  '/doctor/settings': typeof AuthenticatedDoctorSettingsRoute
  '/doctor/users': typeof AuthenticatedDoctorUsersRoute
  '/patient/appointments': typeof AuthenticatedPatientAppointmentsRoute
  '/patient/history': typeof AuthenticatedPatientHistoryRoute
  '/patient/prescriptions': typeof AuthenticatedPatientPrescriptionsRoute
  '/patient/profile': typeof AuthenticatedPatientProfileRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/doctor': typeof AuthenticatedDoctorIndexRoute
  '/patient': typeof AuthenticatedPatientIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/appointment': typeof AppointmentRoute
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRoute
  '/chambers': typeof ChambersRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/portal': typeof PortalRoute
  '/services': typeof ServicesRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/doctor': typeof AuthenticatedDoctorRouteWithChildren
  '/_authenticated/patient': typeof AuthenticatedPatientRouteWithChildren
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/_authenticated/admin/appointments': typeof AuthenticatedAdminAppointmentsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/website': typeof AuthenticatedAdminWebsiteRoute
  '/_authenticated/doctor/appointments': typeof AuthenticatedDoctorAppointmentsRoute
  '/_authenticated/doctor/patients': typeof AuthenticatedDoctorPatientsRoute
  '/_authenticated/doctor/prescriptions': typeof AuthenticatedDoctorPrescriptionsRoute
  '/_authenticated/doctor/reports': typeof AuthenticatedDoctorReportsRoute
  '/_authenticated/doctor/settings': typeof AuthenticatedDoctorSettingsRoute
  '/_authenticated/doctor/users': typeof AuthenticatedDoctorUsersRoute
  '/_authenticated/patient/appointments': typeof AuthenticatedPatientAppointmentsRoute
  '/_authenticated/patient/history': typeof AuthenticatedPatientHistoryRoute
  '/_authenticated/patient/prescriptions': typeof AuthenticatedPatientPrescriptionsRoute
  '/_authenticated/patient/profile': typeof AuthenticatedPatientProfileRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/doctor/': typeof AuthenticatedDoctorIndexRoute
  '/_authenticated/patient/': typeof AuthenticatedPatientIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/appointment'
    | '/auth'
    | '/blog'
    | '/chambers'
    | '/contact'
    | '/gallery'
    | '/portal'
    | '/services'
    | '/admin'
    | '/dashboard'
    | '/doctor'
    | '/patient'
    | '/auth/reset-password'
    | '/admin/appointments'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/website'
    | '/doctor/appointments'
    | '/doctor/patients'
    | '/doctor/prescriptions'
    | '/doctor/reports'
    | '/doctor/settings'
    | '/doctor/users'
    | '/patient/appointments'
    | '/patient/history'
    | '/patient/prescriptions'
    | '/patient/profile'
    | '/admin/'
    | '/doctor/'
    | '/patient/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/appointment'
    | '/auth'
    | '/blog'
    | '/chambers'
    | '/contact'
    | '/gallery'
    | '/portal'
    | '/services'
    | '/dashboard'
    | '/auth/reset-password'
    | '/admin/appointments'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/website'
    | '/doctor/appointments'
    | '/doctor/patients'
    | '/doctor/prescriptions'
    | '/doctor/reports'
    | '/doctor/settings'
    | '/doctor/users'
    | '/patient/appointments'
    | '/patient/history'
    | '/patient/prescriptions'
    | '/patient/profile'
    | '/admin'
    | '/doctor'
    | '/patient'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/appointment'
    | '/auth'
    | '/blog'
    | '/chambers'
    | '/contact'
    | '/gallery'
    | '/portal'
    | '/services'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/doctor'
    | '/_authenticated/patient'
    | '/auth/reset-password'
    | '/_authenticated/admin/appointments'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/website'
    | '/_authenticated/doctor/appointments'
    | '/_authenticated/doctor/patients'
    | '/_authenticated/doctor/prescriptions'
    | '/_authenticated/doctor/reports'
    | '/_authenticated/doctor/settings'
    | '/_authenticated/doctor/users'
    | '/_authenticated/patient/appointments'
    | '/_authenticated/patient/history'
    | '/_authenticated/patient/prescriptions'
    | '/_authenticated/patient/profile'
    | '/_authenticated/admin/'
    | '/_authenticated/doctor/'
    | '/_authenticated/patient/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AppointmentRoute: typeof AppointmentRoute
  AuthRoute: typeof AuthRouteWithChildren
  BlogRoute: typeof BlogRoute
  ChambersRoute: typeof ChambersRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  PortalRoute: typeof PortalRoute
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chambers': {
      id: '/chambers'
      path: '/chambers'
      fullPath: '/chambers'
      preLoaderRoute: typeof ChambersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointment': {
      id: '/appointment'
      path: '/appointment'
      fullPath: '/appointment'
      preLoaderRoute: typeof AppointmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/patient': {
      id: '/_authenticated/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof AuthenticatedPatientRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/doctor': {
      id: '/_authenticated/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof AuthenticatedDoctorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patient/': {
      id: '/_authenticated/patient/'
      path: '/'
      fullPath: '/patient/'
      preLoaderRoute: typeof AuthenticatedPatientIndexRouteImport
      parentRoute: typeof AuthenticatedPatientRoute
    }
    '/_authenticated/doctor/': {
      id: '/_authenticated/doctor/'
      path: '/'
      fullPath: '/doctor/'
      preLoaderRoute: typeof AuthenticatedDoctorIndexRouteImport
      parentRoute: typeof AuthenticatedDoctorRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/patient/profile': {
      id: '/_authenticated/patient/profile'
      path: '/profile'
      fullPath: '/patient/profile'
      preLoaderRoute: typeof AuthenticatedPatientProfileRouteImport
      parentRoute: typeof AuthenticatedPatientRoute
    }
    '/_authenticated/patient/prescriptions': {
      id: '/_authenticated/patient/prescriptions'
      path: '/prescriptions'
      fullPath: '/patient/prescriptions'
      preLoaderRoute: typeof AuthenticatedPatientPrescriptionsRouteImport
      parentRoute: typeof AuthenticatedPatientRoute
    }
    '/_authenticated/patient/history': {
      id: '/_authenticated/patient/history'
      path: '/history'
      fullPath: '/patient/history'
      preLoaderRoute: typeof AuthenticatedPatientHistoryRouteImport
      parentRoute: typeof AuthenticatedPatientRoute
    }
    '/_authenticated/patient/appointments': {
      id: '/_authenticated/patient/appointments'
      path: '/appointments'
      fullPath: '/patient/appointments'
      preLoaderRoute: typeof AuthenticatedPatientAppointmentsRouteImport
      parentRoute: typeof AuthenticatedPatientRoute
    }
    '/_authenticated/doctor/users': {
      id: '/_authenticated/doctor/users'
      path: '/users'
      fullPath: '/doctor/users'
      preLoaderRoute: typeof AuthenticatedDoctorUsersRouteImport
      parentRoute: typeof AuthenticatedDoctorRoute
    }
    '/_authenticated/doctor/settings': {
      id: '/_authenticated/doctor/settings'
      path: '/settings'
      fullPath: '/doctor/settings'
      preLoaderRoute: typeof AuthenticatedDoctorSettingsRouteImport
      parentRoute: typeof AuthenticatedDoctorRoute
    }
    '/_authenticated/doctor/reports': {
      id: '/_authenticated/doctor/reports'
      path: '/reports'
      fullPath: '/doctor/reports'
      preLoaderRoute: typeof AuthenticatedDoctorReportsRouteImport
      parentRoute: typeof AuthenticatedDoctorRoute
    }
    '/_authenticated/doctor/prescriptions': {
      id: '/_authenticated/doctor/prescriptions'
      path: '/prescriptions'
      fullPath: '/doctor/prescriptions'
      preLoaderRoute: typeof AuthenticatedDoctorPrescriptionsRouteImport
      parentRoute: typeof AuthenticatedDoctorRoute
    }
    '/_authenticated/doctor/patients': {
      id: '/_authenticated/doctor/patients'
      path: '/patients'
      fullPath: '/doctor/patients'
      preLoaderRoute: typeof AuthenticatedDoctorPatientsRouteImport
      parentRoute: typeof AuthenticatedDoctorRoute
    }
    '/_authenticated/doctor/appointments': {
      id: '/_authenticated/doctor/appointments'
      path: '/appointments'
      fullPath: '/doctor/appointments'
      preLoaderRoute: typeof AuthenticatedDoctorAppointmentsRouteImport
      parentRoute: typeof AuthenticatedDoctorRoute
    }
    '/_authenticated/admin/website': {
      id: '/_authenticated/admin/website'
      path: '/website'
      fullPath: '/admin/website'
      preLoaderRoute: typeof AuthenticatedAdminWebsiteRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/appointments': {
      id: '/_authenticated/admin/appointments'
      path: '/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AuthenticatedAdminAppointmentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAppointmentsRoute: typeof AuthenticatedAdminAppointmentsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminWebsiteRoute: typeof AuthenticatedAdminWebsiteRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAppointmentsRoute: AuthenticatedAdminAppointmentsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminWebsiteRoute: AuthenticatedAdminWebsiteRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedDoctorRouteChildren {
  AuthenticatedDoctorAppointmentsRoute: typeof AuthenticatedDoctorAppointmentsRoute
  AuthenticatedDoctorPatientsRoute: typeof AuthenticatedDoctorPatientsRoute
  AuthenticatedDoctorPrescriptionsRoute: typeof AuthenticatedDoctorPrescriptionsRoute
  AuthenticatedDoctorReportsRoute: typeof AuthenticatedDoctorReportsRoute
  AuthenticatedDoctorSettingsRoute: typeof AuthenticatedDoctorSettingsRoute
  AuthenticatedDoctorUsersRoute: typeof AuthenticatedDoctorUsersRoute
  AuthenticatedDoctorIndexRoute: typeof AuthenticatedDoctorIndexRoute
}

const AuthenticatedDoctorRouteChildren: AuthenticatedDoctorRouteChildren = {
  AuthenticatedDoctorAppointmentsRoute: AuthenticatedDoctorAppointmentsRoute,
  AuthenticatedDoctorPatientsRoute: AuthenticatedDoctorPatientsRoute,
  AuthenticatedDoctorPrescriptionsRoute: AuthenticatedDoctorPrescriptionsRoute,
  AuthenticatedDoctorReportsRoute: AuthenticatedDoctorReportsRoute,
  AuthenticatedDoctorSettingsRoute: AuthenticatedDoctorSettingsRoute,
  AuthenticatedDoctorUsersRoute: AuthenticatedDoctorUsersRoute,
  AuthenticatedDoctorIndexRoute: AuthenticatedDoctorIndexRoute,
}

const AuthenticatedDoctorRouteWithChildren =
  AuthenticatedDoctorRoute._addFileChildren(AuthenticatedDoctorRouteChildren)

interface AuthenticatedPatientRouteChildren {
  AuthenticatedPatientAppointmentsRoute: typeof AuthenticatedPatientAppointmentsRoute
  AuthenticatedPatientHistoryRoute: typeof AuthenticatedPatientHistoryRoute
  AuthenticatedPatientPrescriptionsRoute: typeof AuthenticatedPatientPrescriptionsRoute
  AuthenticatedPatientProfileRoute: typeof AuthenticatedPatientProfileRoute
  AuthenticatedPatientIndexRoute: typeof AuthenticatedPatientIndexRoute
}

const AuthenticatedPatientRouteChildren: AuthenticatedPatientRouteChildren = {
  AuthenticatedPatientAppointmentsRoute: AuthenticatedPatientAppointmentsRoute,
  AuthenticatedPatientHistoryRoute: AuthenticatedPatientHistoryRoute,
  AuthenticatedPatientPrescriptionsRoute:
    AuthenticatedPatientPrescriptionsRoute,
  AuthenticatedPatientProfileRoute: AuthenticatedPatientProfileRoute,
  AuthenticatedPatientIndexRoute: AuthenticatedPatientIndexRoute,
}

const AuthenticatedPatientRouteWithChildren =
  AuthenticatedPatientRoute._addFileChildren(AuthenticatedPatientRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDoctorRoute: typeof AuthenticatedDoctorRouteWithChildren
  AuthenticatedPatientRoute: typeof AuthenticatedPatientRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDoctorRoute: AuthenticatedDoctorRouteWithChildren,
  AuthenticatedPatientRoute: AuthenticatedPatientRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AppointmentRoute: AppointmentRoute,
  AuthRoute: AuthRouteWithChildren,
  BlogRoute: BlogRoute,
  ChambersRoute: ChambersRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  PortalRoute: PortalRoute,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
