import { createContext, useContext, useState, type ReactNode } from "react";

export type Lang = "en" | "bn";

const T = {
  en: {
    // Navbar
    nav_home: "Home",
    nav_about: "About Doctor",
    nav_services: "Services",
    nav_chambers: "Chambers",
    nav_gallery: "Gallery",
    nav_contact: "Contact",
    nav_book: "Book Appointment",
    nav_account: "Account",
    nav_login: "Login",
    nav_register: "Create account",
    nav_logout: "Logout",
    nav_notSignedIn: "Not signed in",
    nav_signedIn: "Signed in",
    nav_dashboard: "Dashboard",
    nav_myAppointments: "My Appointments",
    nav_myPrescriptions: "My Prescriptions",
    nav_treatmentHistory: "Treatment History",
    nav_profile: "Profile",
    nav_appointments: "Appointments",
    nav_patients: "Patients",
    nav_prescriptions: "Prescriptions",
    nav_reports: "Reports",

    // Hero
    hero_badge: "Now accepting new patients · Shewrapara, Mirpur",
    hero_new: "New",
    hero_title_1: "Technology",
    hero_title_2: "meets",
    hero_title_3: "dentistry.",
    hero_sub: "A premium dental clinic in Dhaka where digital diagnostics, certified implantology and aesthetic precision come together — designed around you, delivered with care.",
    hero_cta_book: "Book Appointment",
    hero_cta_explore: "Explore Services",
    hero_badge_prescriptions: "Digital Prescriptions",
    hero_badge_booking: "Online Appointment Booking",
    hero_badge_implant: "Certified Implantologist",
    hero_badge_bmdc: "BM&DC Registered",
    hero_stat_satisfaction: "Patient Satisfaction",
    hero_stat_satisfaction_val: "4.9 / 5",
    hero_stat_satisfaction_hint: "From 1,200+ visits",
    hero_stat_booking: "Online Booking",
    hero_stat_booking_val: "Real-time slots",
    hero_stat_rx: "Digital Prescription",
    hero_stat_rx_val: "Instant PDF",
    hero_stat_rx_hint: "Verified & signed",
    hero_stat_tech: "Advanced Tech",
    hero_stat_tech_val: "Digital Workflow",
    hero_stat_tech_hint: "3D scan · CAD",

    // Doctor
    doc_eyebrow: "Meet the Specialist",
    doc_bio: "An internationally trained dental surgeon combining clinical excellence with a calm, technology-forward patient experience. Trusted by families across Dhaka for orthodontics, implants and aesthetic dentistry.",
    doc_quote: "Modern dentistry should be precise, predictable and painless. We bring that standard to every patient — every visit.",
    doc_cta_book: "Book a consultation",
    doc_cta_profile: "Read full profile",
    doc_reg: "BMDC Reg. No: 2073 · Oral & Dental Surgeon",
    doc_experience: "Experience",
    doc_experience_val: "12+ yrs",
    doc_patients: "Patients",
    doc_patients_val: "1,200+",
    doc_training_ortho: "Orthodontics & Implantology",
    doc_training_ortho_note: "Special training, AIC Korea",
    doc_training_cosmetic: "Cosmetic Dentistry",
    doc_training_cosmetic_note: "Trained in Dubai",
    doc_training_prof: "Professor & Head",
    doc_training_prof_note: "Pediatric Dentistry, Marks Medical College",
    doc_training_ada: "Member of ADA",
    doc_training_ada_note: "American Dental Association (USA)",
    doc_intro_bio: "Internationally trained dental surgeon specializing in orthodontics, implantology and aesthetic dentistry — trusted by families across Dhaka.",

    // Chambers
    cham_eyebrow: "Chamber & Location",
    cham_title: "Our chamber,",
    cham_title_brand: "your care.",
    cham_sub: "Conveniently located and equipped for modern, minimally-invasive dental procedures.",
    cham_visiting: "Visiting Hours",
    cham_book: "Book at",
    cham_call: "Call",
    cham_directions: "Directions",
    cham_accepting: "Accepting bookings",

    // Footer
    foot_tagline: "Advanced dental care powered by precision, innovation and a deeply personalized patient experience.",
    foot_clinic: "Clinic",
    foot_about: "About Doctor",
    foot_services: "Services",
    foot_chambers: "Chambers",
    foot_gallery: "Gallery",
    foot_patients: "Patients",
    foot_book: "Book Appointment",
    foot_portal: "Patient Portal",
    foot_blog: "Oral Health Blog",
    foot_contact: "Contact",
    foot_reach: "Reach Us",
    foot_rights: "All rights reserved.",
    foot_hours: "Sun, Tue & Thu · 6PM–9PM",

    // CTA
    cta_badge: "Real-time availability",
    cta_title: "Your next appointment is one tap away.",
    cta_sub: "Live slots. Confirmed instantly. No email required — just your phone number.",
    cta_btn: "Book Appointment",
    cta_location: "Shewrapara, Mirpur · Open by appointment",

    // Services overview (homepage)
    svc_eyebrow: "Services",
    svc_title: "Comprehensive",
    svc_title_brand: "dental care",
    svc_general: "General Dentistry",
    svc_preventive: "Preventive Dentistry",
    svc_restorative: "Restorative Dentistry",
    svc_surgery: "Oral Surgery",
    svc_ortho: "Orthodontics",
    svc_implant: "Implant Dentistry",
    svc_view_all: "View All Services",

    // Services section (full page)
    svc_section_eyebrow: "Services",
    svc_section_title: "Every treatment,",
    svc_section_brand: "engineered around you.",
    svc_section_desc: "From routine checkups to certified implants and full smile design — all delivered with a digital, patient-first workflow.",
    svc_view_all_link: "View all services",
    svc_learn_more: "Learn more →",
    svc_common_reasons: "Common reasons",

    // Page heroes
    page_chambers_eyebrow: "Chambers & Locations",
    page_chambers_title: "Our",
    page_chambers_brand: "chamber",
    page_chambers_desc: "Techno Dental Care — Shewrapara, Mirpur, Dhaka. Equipped for modern, minimally-invasive dental care.",
    page_svc_eyebrow: "Services",
    page_svc_title: "A complete",
    page_svc_brand: "dental ecosystem.",
    page_svc_desc: "From routine checkups to certified implants and full smile design — every treatment, engineered around you.",
    page_about_eyebrow: "About",
    page_about_title: "A doctor who treats dentistry as",
    page_about_brand: "precision craft.",
    page_about_desc: "Internationally trained dental surgeon combining clinical excellence with a calm, technology-forward patient experience.",
    page_contact_eyebrow: "Contact",
    page_contact_title: "We're",
    page_contact_brand: "a tap away.",
    page_contact_desc: "Talk to our team — by phone, WhatsApp or in-person at our chamber.",
    page_gallery_eyebrow: "Gallery",
    page_gallery_title: "A glimpse",
    page_gallery_brand: "inside our clinic.",
    page_gallery_desc: "Real clinic photos coming soon — gallery is structured so we can swap them in instantly.",

    // Contact page cards
    contact_call_title: "Call us",
    contact_clinic: "Techno Dental Care",
    contact_book_online: "Online Booking",
    contact_real_time: "Real-time slots",
    contact_whatsapp: "WhatsApp",
    contact_whatsapp_sub: "Quick message",
    contact_book_btn: "Book Appointment",

    // Dashboard
    dash_manage_users: "Manage Users",
    dash_settings: "Settings",
    dash_patient_role: "Patient",
    dash_doctor_role: "Doctor · Admin",
    dash_portal: "Portal",
    dash_back_site: "Back to site",
    dash_sign_out: "Sign out",
    dash_mobile_site: "Site",

    // Booking flow
    book_eyebrow: "Appointment",
    book_title: "Reserve your",
    book_title_brand: "time slot.",
    book_sub: "Four quick steps. Real-time availability. We'll text confirmation on the phone you provide.",
    book_step_of: "of",
    book_step_complete: "complete",
    book_step_chamber: "Chamber",
    book_step_date: "Date",
    book_step_time: "Time",
    book_step_details: "Details",
    book_step_account: "Account",
    book_step_confirm: "Confirm",
    book_chamber_title: "Choose a chamber",
    book_chamber_sub: "Pick the location most convenient for you.",
    book_chamber_loading: "Loading chambers…",
    book_date_title: "Choose a date",
    book_date_sub: "Showing the next available days at",
    book_time_title: "Choose a time slot",
    book_time_sub: "30-minute slots",
    book_time_checking: "Checking availability…",
    book_details_title: "Your details",
    book_field_name: "Full name",
    book_field_phone: "Phone",
    book_field_age: "Age",
    book_field_email_opt: "Email (optional)",
    book_field_service: "Service of interest",
    book_field_notes: "Notes",
    book_continue: "Continue",
    book_back: "← Back",
    book_account_badge: "Almost done — sign in to confirm",
    book_account_title: "Login or create account",
    book_account_sub: "We use your account to manage and track your visit. It only takes a moment.",
    book_tab_signin: "Sign in",
    book_tab_register: "Create account",
    book_field_fullname: "Full name",
    book_field_phone_reg: "Phone (recommended — lets you log in by phone)",
    book_field_identifier: "Email or phone number",
    book_field_email_reg: "Email",
    book_field_password: "Password",
    book_btn_signin: "Sign in & confirm",
    book_btn_register: "Create account & confirm",
    book_confirming: "Confirming your appointment…",
    book_success_title: "Appointment confirmed",
    book_success_sub: "We've reserved your slot. Save your booking code — you'll need it to manage or cancel.",
    book_code_label: "Booking code",
    book_copy: "Copy",
    book_date_label: "Date",
    book_time_label: "Time",
    book_chamber_label_booking: "Chamber",
    book_call_clinic: "Call clinic",
    book_book_another: "Book another",
    book_encrypted: "Encrypted & stored securely · BM&DC-registered clinic",
    book_confirming_as: "Confirming as",

    // Prescription labels
    rx_title: "Digital Prescription",
    rx_patient: "Patient Name",
    rx_age: "Age",
    rx_date: "Date",
    rx_phone: "Phone",
    rx_complaint: "Chief Complaint",
    rx_diagnosis: "Diagnosis",
    rx_medicines: "Medicines / Prescription",
    rx_medicine: "Medicine Name",
    rx_dosage: "Dosage",
    rx_frequency: "Frequency",
    rx_duration: "Duration",
    rx_notes: "Notes",
    rx_instructions: "Instructions",
    rx_followup: "Follow-up Date",
    rx_signature: "Doctor's Signature",
    rx_stamp: "SEAL / STAMP",
    rx_footer: "This prescription was digitally issued by Techno Dental Care · BMDC Reg. No: 2073",
    rx_print: "Print / Save PDF",
    rx_print_bn: "বাংলায় প্রিন্ট",
    rx_num: "No.",
    rx_days: "yrs",
  },
  bn: {
    // Navbar
    nav_home: "হোম",
    nav_about: "ডাক্তার পরিচিতি",
    nav_services: "সেবা",
    nav_chambers: "চেম্বার",
    nav_gallery: "গ্যালারি",
    nav_contact: "যোগাযোগ",
    nav_book: "অ্যাপয়েন্টমেন্ট নিন",
    nav_account: "অ্যাকাউন্ট",
    nav_login: "লগইন",
    nav_register: "অ্যাকাউন্ট তৈরি করুন",
    nav_logout: "লগআউট",
    nav_notSignedIn: "লগইন করা হয়নি",
    nav_signedIn: "লগইন করা হয়েছে",
    nav_dashboard: "ড্যাশবোর্ড",
    nav_myAppointments: "আমার অ্যাপয়েন্টমেন্ট",
    nav_myPrescriptions: "আমার প্রেসক্রিপশন",
    nav_treatmentHistory: "চিকিৎসার ইতিহাস",
    nav_profile: "প্রোফাইল",
    nav_appointments: "অ্যাপয়েন্টমেন্ট",
    nav_patients: "রোগী",
    nav_prescriptions: "প্রেসক্রিপশন",
    nav_reports: "রিপোর্ট",

    // Hero — culturally distinct Bengali tagline (not a direct translation)
    hero_badge: "নতুন রোগী নেওয়া হচ্ছে · শেওড়াপাড়া, মিরপুর",
    hero_new: "নতুন",
    hero_title_1: "হাসুন",
    hero_title_2: "নির্ভয়ে,",
    hero_title_3: "সুস্থ দাঁতে।",
    hero_sub: "ঢাকার একটি প্রিমিয়াম ডেন্টাল ক্লিনিক যেখানে ডিজিটাল ডায়াগনস্টিক্স, সার্টিফাইড ইমপ্লান্টোলজি ও নান্দনিক দক্ষতা একসাথে — আপনার জন্য, আপনার সেবায়।",
    hero_cta_book: "অ্যাপয়েন্টমেন্ট নিন",
    hero_cta_explore: "সেবাসমূহ দেখুন",
    hero_badge_prescriptions: "ডিজিটাল প্রেসক্রিপশন",
    hero_badge_booking: "অনলাইন অ্যাপয়েন্টমেন্ট",
    hero_badge_implant: "সার্টিফাইড ইমপ্লান্টোলজিস্ট",
    hero_badge_bmdc: "বিএমডিসি নিবন্ধিত",
    hero_stat_satisfaction: "রোগী সন্তুষ্টি",
    hero_stat_satisfaction_val: "৪.৯ / ৫",
    hero_stat_satisfaction_hint: "১,২০০+ ভিজিট থেকে",
    hero_stat_booking: "অনলাইন বুকিং",
    hero_stat_booking_val: "রিয়েল-টাইম স্লট",
    hero_stat_rx: "ডিজিটাল প্রেসক্রিপশন",
    hero_stat_rx_val: "তাৎক্ষণিক PDF",
    hero_stat_rx_hint: "যাচাইকৃত ও স্বাক্ষরিত",
    hero_stat_tech: "উন্নত প্রযুক্তি",
    hero_stat_tech_val: "ডিজিটাল ওয়ার্কফ্লো",
    hero_stat_tech_hint: "৩D স্ক্যান · CAD",

    // Doctor
    doc_eyebrow: "বিশেষজ্ঞের সাথে পরিচয়",
    doc_bio: "আন্তর্জাতিকভাবে প্রশিক্ষিত একজন ডেন্টাল সার্জন যিনি ক্লিনিক্যাল দক্ষতা ও আধুনিক প্রযুক্তিকে একত্রিত করেন। অর্থোডন্টিক্স, ইমপ্লান্ট ও নান্দনিক দন্তচিকিৎসায় ঢাকার পরিবারগুলোর বিশ্বস্ত চিকিৎসক।",
    doc_quote: "আধুনিক দন্তচিকিৎসা হওয়া উচিত নির্ভুল, নিশ্চিত ও ব্যথামুক্ত। আমরা প্রতিটি রোগীর জন্য সেই মানদণ্ড নিশ্চিত করি — প্রতিটি ভিজিটে।",
    doc_cta_book: "পরামর্শের জন্য বুক করুন",
    doc_cta_profile: "সম্পূর্ণ প্রোফাইল দেখুন",
    doc_reg: "বিএমডিসি নিবন্ধন: ২০৭৩ · ওরাল ও ডেন্টাল সার্জন",
    doc_experience: "অভিজ্ঞতা",
    doc_experience_val: "১২+ বছর",
    doc_patients: "রোগী",
    doc_patients_val: "১,২০০+",
    doc_training_ortho: "অর্থোডন্টিক্স ও ইমপ্লান্টোলজি",
    doc_training_ortho_note: "বিশেষ প্রশিক্ষণ, AIC কোরিয়া",
    doc_training_cosmetic: "কসমেটিক ডেন্টিস্ট্রি",
    doc_training_cosmetic_note: "দুবাইতে প্রশিক্ষণ",
    doc_training_prof: "অধ্যাপক ও বিভাগীয় প্রধান",
    doc_training_prof_note: "শিশু দন্তচিকিৎসা, মার্কস মেডিকেল কলেজ",
    doc_training_ada: "ADA সদস্য",
    doc_training_ada_note: "আমেরিকান ডেন্টাল অ্যাসোসিয়েশন (USA)",
    doc_intro_bio: "অর্থোডন্টিক্স, ইমপ্লান্টোলজি ও নান্দনিক দন্তচিকিৎসায় বিশেষজ্ঞ আন্তর্জাতিকভাবে প্রশিক্ষিত ডেন্টাল সার্জন — ঢাকার পরিবারগুলোর বিশ্বস্ত চিকিৎসক।",

    // Chambers
    cham_eyebrow: "চেম্বার ও অবস্থান",
    cham_title: "আমাদের চেম্বার,",
    cham_title_brand: "আপনার সেবায়।",
    cham_sub: "আধুনিক, ন্যূনতম আক্রমণাত্মক দন্তচিকিৎসার জন্য সুবিধাজনক অবস্থানে সজ্জিত।",
    cham_visiting: "ভিজিটিং আওয়ার",
    cham_book: "বুক করুন",
    cham_call: "কল করুন",
    cham_directions: "দিকনির্দেশনা",
    cham_accepting: "বুকিং নেওয়া হচ্ছে",

    // Footer
    foot_tagline: "নির্ভুলতা, উদ্ভাবন ও ব্যক্তিগতকৃত রোগী-অভিজ্ঞতার মাধ্যমে উন্নত দন্তসেবা।",
    foot_clinic: "ক্লিনিক",
    foot_about: "ডাক্তার পরিচিতি",
    foot_services: "সেবা",
    foot_chambers: "চেম্বার",
    foot_gallery: "গ্যালারি",
    foot_patients: "রোগী",
    foot_book: "অ্যাপয়েন্টমেন্ট নিন",
    foot_portal: "রোগী পোর্টাল",
    foot_blog: "মুখস্বাস্থ্য ব্লগ",
    foot_contact: "যোগাযোগ",
    foot_reach: "আমাদের সাথে যোগাযোগ",
    foot_rights: "সর্বস্বত্ব সংরক্ষিত।",
    foot_hours: "রবি, মঙ্গল ও বৃহস্পতি · সন্ধ্যা ৬টা–রাত ৯টা",

    // CTA
    cta_badge: "রিয়েল-টাইম প্রাপ্যতা",
    cta_title: "পরবর্তী অ্যাপয়েন্টমেন্ট মাত্র এক ট্যাপেই।",
    cta_sub: "লাইভ স্লট। তাৎক্ষণিক নিশ্চিতকরণ। শুধু ফোন নম্বর দিন।",
    cta_btn: "অ্যাপয়েন্টমেন্ট নিন",
    cta_location: "শেওড়াপাড়া, মিরপুর · অ্যাপয়েন্টমেন্টে খোলা",

    // Services overview (homepage)
    svc_eyebrow: "সেবা",
    svc_title: "সম্পূর্ণ",
    svc_title_brand: "দন্তসেবা",
    svc_general: "সাধারণ দন্তচিকিৎসা",
    svc_preventive: "প্রতিরোধমূলক দন্তচিকিৎসা",
    svc_restorative: "পুনরুদ্ধারমূলক দন্তচিকিৎসা",
    svc_surgery: "ওরাল সার্জারি",
    svc_ortho: "অর্থোডন্টিক্স",
    svc_implant: "ইমপ্লান্ট ডেন্টিস্ট্রি",
    svc_view_all: "সব সেবা দেখুন",

    // Services section (full page)
    svc_section_eyebrow: "সেবা",
    svc_section_title: "প্রতিটি চিকিৎসা,",
    svc_section_brand: "আপনাকে ঘিরে।",
    svc_section_desc: "রুটিন চেকআপ থেকে সার্টিফাইড ইমপ্লান্ট ও স্মাইল ডিজাইন পর্যন্ত — ডিজিটাল, রোগী-প্রথম ওয়ার্কফ্লোতে।",
    svc_view_all_link: "সব সেবা দেখুন",
    svc_learn_more: "আরও জানুন →",
    svc_common_reasons: "সাধারণ কারণ",

    // Page heroes
    page_chambers_eyebrow: "চেম্বার ও অবস্থান",
    page_chambers_title: "আমাদের",
    page_chambers_brand: "চেম্বার",
    page_chambers_desc: "টেকনো ডেন্টাল কেয়ার — শেওড়াপাড়া, মিরপুর, ঢাকা। আধুনিক দন্তচিকিৎসার জন্য সজ্জিত।",
    page_svc_eyebrow: "সেবাসমূহ",
    page_svc_title: "সম্পূর্ণ",
    page_svc_brand: "দন্তসেবার কেন্দ্র।",
    page_svc_desc: "রুটিন চেকআপ থেকে সার্টিফাইড ইমপ্লান্ট ও স্মাইল ডিজাইন পর্যন্ত — প্রতিটি চিকিৎসা আপনাকে ঘিরে।",
    page_about_eyebrow: "পরিচিতি",
    page_about_title: "দন্তচিকিৎসাকে যিনি দেখেন",
    page_about_brand: "নির্ভুল শিল্প হিসেবে।",
    page_about_desc: "আন্তর্জাতিকভাবে প্রশিক্ষিত ডেন্টাল সার্জন যিনি ক্লিনিক্যাল দক্ষতা ও আধুনিক প্রযুক্তিকে একত্রিত করেন।",
    page_contact_eyebrow: "যোগাযোগ",
    page_contact_title: "আমরা",
    page_contact_brand: "এক ট্যাপেই।",
    page_contact_desc: "ফোন, হোয়াটসঅ্যাপ বা সরাসরি — আমাদের দলের সাথে কথা বলুন।",
    page_gallery_eyebrow: "গ্যালারি",
    page_gallery_title: "একটি ঝলক",
    page_gallery_brand: "আমাদের ক্লিনিকের।",
    page_gallery_desc: "আসল ক্লিনিকের ছবি শীঘ্রই আসছে — গ্যালারি প্রস্তুত আছে।",

    // Contact page cards
    contact_call_title: "কল করুন",
    contact_clinic: "টেকনো ডেন্টাল কেয়ার",
    contact_book_online: "অনলাইন বুকিং",
    contact_real_time: "রিয়েল-টাইম স্লট",
    contact_whatsapp: "হোয়াটসঅ্যাপ",
    contact_whatsapp_sub: "দ্রুত বার্তা",
    contact_book_btn: "অ্যাপয়েন্টমেন্ট নিন",

    // Dashboard
    dash_manage_users: "ব্যবহারকারী ব্যবস্থাপনা",
    dash_settings: "সেটিংস",
    dash_patient_role: "রোগী",
    dash_doctor_role: "ডাক্তার · অ্যাডমিন",
    dash_portal: "পোর্টাল",
    dash_back_site: "সাইটে ফিরুন",
    dash_sign_out: "সাইন আউট",
    dash_mobile_site: "সাইট",

    // Booking flow
    book_eyebrow: "অ্যাপয়েন্টমেন্ট",
    book_title: "আপনার",
    book_title_brand: "সময় বুক করুন।",
    book_sub: "চারটি সহজ ধাপ। রিয়েল-টাইম প্রাপ্যতা। আপনার দেওয়া ফোনে কনফার্মেশন পাঠানো হবে।",
    book_step_of: "এর মধ্যে",
    book_step_complete: "সম্পন্ন",
    book_step_chamber: "চেম্বার",
    book_step_date: "তারিখ",
    book_step_time: "সময়",
    book_step_details: "বিস্তারিত",
    book_step_account: "অ্যাকাউন্ট",
    book_step_confirm: "নিশ্চিত",
    book_chamber_title: "চেম্বার বেছে নিন",
    book_chamber_sub: "আপনার সুবিধামতো স্থান বেছে নিন।",
    book_chamber_loading: "চেম্বার লোড হচ্ছে…",
    book_date_title: "তারিখ বেছে নিন",
    book_date_sub: "পরবর্তী উপলব্ধ দিন দেখাচ্ছে:",
    book_time_title: "সময় বেছে নিন",
    book_time_sub: "৩০ মিনিটের স্লট",
    book_time_checking: "প্রাপ্যতা যাচাই হচ্ছে…",
    book_details_title: "আপনার তথ্য",
    book_field_name: "পূর্ণ নাম",
    book_field_phone: "ফোন",
    book_field_age: "বয়স",
    book_field_email_opt: "ইমেইল (ঐচ্ছিক)",
    book_field_service: "পছন্দের সেবা",
    book_field_notes: "মন্তব্য",
    book_continue: "পরবর্তী",
    book_back: "← পিছনে",
    book_account_badge: "প্রায় শেষ — নিশ্চিত করতে সাইন ইন করুন",
    book_account_title: "লগইন বা অ্যাকাউন্ট তৈরি করুন",
    book_account_sub: "আপনার ভিজিট পরিচালনা করতে অ্যাকাউন্ট ব্যবহার করা হয়। মাত্র এক মিনিট লাগবে।",
    book_tab_signin: "সাইন ইন",
    book_tab_register: "অ্যাকাউন্ট তৈরি করুন",
    book_field_fullname: "পূর্ণ নাম",
    book_field_phone_reg: "ফোন (প্রস্তাবিত — ফোনে লগইন করতে পারবেন)",
    book_field_identifier: "ইমেইল বা ফোন নম্বর",
    book_field_email_reg: "ইমেইল",
    book_field_password: "পাসওয়ার্ড",
    book_btn_signin: "সাইন ইন ও নিশ্চিত করুন",
    book_btn_register: "অ্যাকাউন্ট তৈরি ও নিশ্চিত করুন",
    book_confirming: "অ্যাপয়েন্টমেন্ট নিশ্চিত হচ্ছে…",
    book_success_title: "অ্যাপয়েন্টমেন্ট নিশ্চিত হয়েছে",
    book_success_sub: "আপনার স্লট সংরক্ষিত হয়েছে। বুকিং কোড সেভ করুন — বাতিল বা পরিচালনার জন্য প্রয়োজন হবে।",
    book_code_label: "বুকিং কোড",
    book_copy: "কপি করুন",
    book_date_label: "তারিখ",
    book_time_label: "সময়",
    book_chamber_label_booking: "চেম্বার",
    book_call_clinic: "ক্লিনিকে কল করুন",
    book_book_another: "আরেকটি বুক করুন",
    book_encrypted: "এনক্রিপ্টেড ও নিরাপদভাবে সংরক্ষিত · বিএমডিসি নিবন্ধিত ক্লিনিক",
    book_confirming_as: "নিশ্চিত হচ্ছে:",

    // Prescription labels (Bengali)
    rx_title: "ডিজিটাল প্রেসক্রিপশন",
    rx_patient: "রোগীর নাম",
    rx_age: "বয়স",
    rx_date: "তারিখ",
    rx_phone: "ফোন",
    rx_complaint: "প্রধান সমস্যা",
    rx_diagnosis: "রোগ নির্ণয়",
    rx_medicines: "ওষুধ / প্রেসক্রিপশন",
    rx_medicine: "ওষুধের নাম",
    rx_dosage: "মাত্রা",
    rx_frequency: "সেবনবিধি",
    rx_duration: "সময়কাল",
    rx_notes: "বিশেষ টীকা",
    rx_instructions: "নির্দেশনা",
    rx_followup: "পরবর্তী ভিজিটের তারিখ",
    rx_signature: "চিকিৎসকের স্বাক্ষর",
    rx_stamp: "সিল / স্ট্যাম্প",
    rx_footer: "এই প্রেসক্রিপশনটি টেকনো ডেন্টাল কেয়ার কর্তৃক ডিজিটালি ইস্যু করা হয়েছে · বিএমডিসি নিবন্ধন: ২০৭৩",
    rx_print: "প্রিন্ট / PDF সেভ করুন",
    rx_print_bn: "Print in English",
    rx_num: "নং",
    rx_days: "বছর",
  },
} as const;

export type TKey = keyof typeof T.en;

const Ctx = createContext<{ lang: Lang; t: (k: TKey) => string; toggle: () => void } | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>(() => {
    try { return (localStorage.getItem("dental_lang") as Lang) ?? "en"; } catch { return "en"; }
  });

  function toggle() {
    setLang((l) => {
      const next = l === "en" ? "bn" : "en";
      try { localStorage.setItem("dental_lang", next); } catch { /* ignore */ }
      return next;
    });
  }

  function t(key: TKey): string {
    return T[lang][key] as string;
  }

  return <Ctx.Provider value={{ lang, t, toggle }}>{children}</Ctx.Provider>;
}

export function useLanguage() {
  const ctx = useContext(Ctx);
  if (!ctx) throw new Error("useLanguage must be inside LanguageProvider");
  return ctx;
}
